services:
  php:
    build: ./docker
    volumes:
      - ./docker/msmtprc:/etc/msmtprc:ro
      - ./:/var/www
    env_file: smtp.env
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www:ro
    ports:
      - "8080:80"
    depends_on:
      - php
